/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/objectives': typeof ObjectivesRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/objectives': typeof ObjectivesRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/objectives': typeof ObjectivesRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/objectives'
    | '/process'
    | '/services'
    | '/why-choose-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/objectives'
    | '/process'
    | '/services'
    | '/why-choose-us'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/objectives'
    | '/process'
    | '/services'
    | '/why-choose-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ObjectivesRoute: typeof ObjectivesRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ObjectivesRoute: ObjectivesRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
